name: WesternOulets
favicon: null
layout_spectrum: 0.2153865189757198
typography_spectrum: 0.6983206269796938
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4336627742741257
  lightness: 0.3685930965002626
  saturation: 0.3898931264411658
  rhythmicContrast: 0.6098560595419258
purpose: []
